services:
  web:
    build:
      context: ./src
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=Devsu;Username=postgres;Password=postgres
      - LICENSE_KEY=IRONSUITE.ORBIS.ALONZO.UNICARIBE.EDU.DO.8326-C5C3E2FB5B-G6BW27T56NMHDS-VBLXRNHM4QF5-2T323ZHMLHIQ-UN4IVXVSIAEZ-KE2UEVSSIBIF-OEYDE2J3LDQV-RA6PKB-TGYJBEY6MDGQEA-DEPLOYMENT.TRIAL-LBWCQX.TRIAL.EXPIRES.22.AUG.2025
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    platform: linux/amd64
    restart: unless-stopped
    environment:
      - POSTGRES_DB=Devsu
      - POSTGRES_USER=postgres  
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
volumes:
  pgdata: