services:
  web:
    build:
      context: ./src
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=Devsu;Username=postgres;Password=postgres
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    platform: linux/amd64
    restart: unless-stopped
    environment:
      - POSTGRES_DB=Devsu
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d Devsu"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  pgdata: